name: buildvarstet
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # additional intl from dart.dev
  intl: ^0.17.0
  # logging
  logging: ^1.0.2
  # logging appenders
  logging_appenders: ^1.0.0
  ## app exceptions capturing
  catcher: ^0.6.9
  # design guides
  design_tools: ^0.3.0
  # custom fonts
  google_fonts: ^3.0.1
  # util for new color space
  material_color_utilities: ^0.2.0
  # better themes, fills material themes gaps
  flex_color_scheme: ^6.0.0
  # screenshots
  screenshot_modes: ^1.0.1
  # device frame 
  device_preview: ^1.1.0
  # rive animation
  rive: ^0.9.1
  # lifecycle events
  lifecycle: ^0.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  # dart code metrics and extra lints
  dart_code_metrics: ^4.18.1
  # better lint
  lint: ^1.10.0

dependency_overrides:
  material_color_utilities: ^0.2.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/google_fonts/
    - assets/rive/
