name: vscodesetup
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # additional intl from dart.dev
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # dart code metrics and extra lints
  dart_code_metrics: ^4.18.1
  # better lint
  lint: ^1.10.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    # google fonts can go in subfolder of assets as that package
    # loads the assets manifest to check for local fonts before
    # http operations
    - assets/images/
